export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

export const SET_COLOR_TYPE = 'SET_COLOR_TYPE';
export const SET_SELECTED_COLOR = 'SET_SELECTED_COLOR';
