export const ADD_PUBLIC_PALETTE = 'ADD_PUBLIC_PALETTES';
export const UPDATE_PUBLIC_PALETTE_LIKES = 'UPDATE_PUBLIC_PALETTE_LIKES';
export const CLEAR_PUBLIC_PALETTES = 'CLEAR_PUBLIC_PALETTES';
export const ADD_PUBLIC_PALETTES_TO_END = 'ADD_PUBLIC_PALETTES_TO_END';
export const SET_PALETTES_WAS_ADDED = 'SET_PALETTES_WAS_ADDED';
export const START_LOADING_PUBLIC = 'START_LOADING_PUBLIC';
export const STOP_LOADING_PUBLIC = 'STOP_LOADING_PUBLIC';
export const SET_NO_MORE_PALETTES = 'SET_NO_MORE_PALETTES';
