export const ADD_PUBLIC_PALETTE = 'ADD_PUBLIC_PALETTES';
export const UPDATE_PUBLIC_PALETTE_LIKES = 'UPDATE_PUBLIC_PALETTE_LIKES';
export const CLEAR_PUBLIC_PALETTES = 'CLEAR_PUBLIC_PALETTES';
export const ADD_PUBLIC_PALETTES_TO_END = 'ADD_PUBLIC_PALETTES_TO_END';

export const COPY_TO_USER_PALETTES = 'COPY_TO_USER_PALETTES';
