export const ADD_USER_PALETTE = 'ADD_USER_PALETTE';
export const UPDATE_USER_PALETTE_COLOR = 'UPDATE_USER_PALETTE_COLOR';
export const UPDATE_USER_PALETTE_COLORS = 'UPDATE_USER_PALETTE_COLORS';
export const UPDATE_USER_PALETTE_LIKES = 'UPDATE_USER_PALETTE_LIKES';
export const MAKE_PALETTE_PUBLIC = 'MAKE_PALETTE_PUBLIC';
export const REMOVE_USER_PALETTE = 'REMOVE_USER_PALETTE';
export const CLEAR_USER_PALETTES = 'CLEAR_USER_PALETTES';
export const ADD_USER_PALETTES_TO_END = 'ADD_USER_PALETTES_TO_END';
